---
apiVersion: v1
kind: Service
metadata:
  name: postgresdb
  namespace: sonarqube
  labels:
    app: postgresdb
spec:
  type: NodePort
  ports:
  - name: postgres
    protocol: TCP
    port: 5432
    targetPort: 5432
  selector:
    app: postgresdb
