---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-nfs
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /postgres-sonar
    server: 10.112.42.52
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc-nfs
  namespace: sonarqube
  labels:
    app: postgresdb
spec:
  accessModes:
  - ReadWriteMany
  resources:
     requests:
       storage: 5Gi

