---
apiVersion: v1
kind: Service
metadata:
  name: postgresdb-svc
  namespace: sonarqube
  labels:
    app: postgresdb
spec:
  ports:
  - name: postgres
    protocol: TCP
    port: 5432
    targetPort: 5432
  selector:
    app: postgresdb
