--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: sonarqube
  name: sonarqube
  namespace: sonarqube
spec:
  replicas: 1
  selector: 
    matchLabels: 
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube  
    spec: 
      initContainers:
          - name: set-vm-max-map-count
            image: busybox
            imagePullPolicy: IfNotPresent
            securityContext:
              privileged: true
            command: ['sh', '-c',"sysctl -w vm.max_map_count=524288"]
      containers:
        - env: 
            - name: SONARQUBE_JDBC_USERNAME
              value: "sonarqube"
            - name: SONARQUBE_JDBC_URL
              value: "jdbc:postgresql://10.112.42.75:32452/sonardb"
            - name: SONARQUBE_JDBC_PASSWORD
              value: "password"
          image: quay.io/appcontainers/sonarqube
          name: sonarqube-pod
          ports: 
            - containerPort: 9000
              protocol: TCP
          resources: 
            limits: 
              cpu: 2000m
              memory: 2048Mi
            requests: 
              cpu: 500m
              memory: 1024Mi
          volumeMounts: 
            - mountPath: /opt/sonarqube/data/
              name: sonarqube-data
            - mountPath: /opt/sonarqube/extensions/
              name: sonarqube-extensions
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
        - 8.8.8.8        
      volumes: 
        - name: sonarqube-data
          persistentVolumeClaim: 
            claimName: sonar-datapv-claim
        - name: sonarqube-extensions
          persistentVolumeClaim: 
            claimName: sonar-extensionspv-claim
