---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonar-pv-nfs
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /sonar
    server: 10.112.42.52
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonar-extensionspv-claim
  namespace: sonarqube
  labels:
    app: sonarqube
spec:
  accessModes:
  - ReadWriteMany
  resources:
     requests:
       storage: 5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonar-data-pv-nfs
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /sonar-data
    server: 10.112.42.52
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonar-datapv-claim
  namespace: sonarqube
  labels:
    app: sonarqube
spec:
  accessModes:
  - ReadWriteMany
  resources:
     requests:
       storage: 5Gi
--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: sonarqube
  name: sonarqube
  namespace: sonarqube
spec:
  replicas: 1
  selector: 
    matchLabels: 
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube  
    spec: 
      initContainers:
          - name: set-vm-max-map-count
            image: busybox
            imagePullPolicy: IfNotPresent
            securityContext:
              privileged: true
            command: ['sh', '-c',"sysctl -w vm.max_map_count=524288"]
      containers:
        - env: 
            - name: SONARQUBE_JDBC_USERNAME
              value: "sonarqube"
            - name: SONARQUBE_JDBC_URL
              value: "jdbc:postgresql://10.112.42.75:32452/sonardb"
            - name: SONARQUBE_JDBC_PASSWORD
              value: "password"
          image: quay.io/appcontainers/sonarqube
          name: sonarqube-pod
          ports: 
            - containerPort: 9000
              protocol: TCP
          resources: 
            limits: 
              cpu: 2000m
              memory: 2048Mi
            requests: 
              cpu: 500m
              memory: 1024Mi
          volumeMounts: 
            - mountPath: /opt/sonarqube/data/
              name: sonarqube-data
            - mountPath: /opt/sonarqube/extensions/
              name: sonarqube-extensions
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
        - 8.8.8.8        
      volumes: 
        - name: sonarqube-data
          persistentVolumeClaim: 
            claimName: sonar-datapv-claim
        - name: sonarqube-extensions
          persistentVolumeClaim: 
            claimName: sonar-extensionspv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: sonarqube-lb
  namespace: sonarqube
spec:
  type: LoadBalancer
  selector:
    app: sonarqube
  ports:
  - name: http
    port: 80
    targetPort: 9000
  sessionAffinity: ClientIP
