---
apiVersion: v1
kind: Service
metadata:
  name: sonarqube-lb
  namespace: sonarqube
spec:
  type: LoadBalancer
  selector:
    app: sonarqube
  ports:
  - name: http
    port: 80
    targetPort: 9000
  sessionAffinity: ClientIP
