---
apiVersion: v1
kind: PersistentVolume
metadata:
   name: prometheus-storage-pv-nfs
   namespace: monitoring
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /prometheus-storage
    server: 10.112.42.52
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-storage-pvc-nfs
  namespace: monitoring
  labels:
    app: prometheus-server
spec:
  accessModes:
  - ReadWriteMany
  resources:
     requests:
       storage: 5Gi
