---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv-nfs
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /grafana
    server: 10.112.42.52
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc-nfs
  namespace: monitoring
  labels:
    app: grafana
spec:
  accessModes:
  - ReadWriteMany
  resources:
     requests:
       storage: 5Gi

