---
apiVersion: v1
kind: PersistentVolume
metadata:
   name: gogs-pv-nfs
   namespace: source-control
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 9Gi
  persistentVolumeReclaimPolicy: Retain 
  nfs: 
    path: /gogs
    server: 10.112.42.52
    readOnly: false
