---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gogs-pvc-nfs
  namespace: source-control
  labels:
    app: gogs
spec:
  accessModes:
  - ReadWriteMany
  resources:
     requests:
       storage: 9Gi
