---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gogs
  namespace: source-control
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gogs
  template:
    metadata:
      labels:
        app: gogs
        istio-injection: enabled
        version: v1
    spec:
      securityContext:
        fsGroup: 2000
      containers:
      - name: gogs
        image: gogs/gogs:0.11.91
        ports:
        - containerPort: 22
          name: ssh
        - containerPort: 3000
          name: http
        env:
        - name: SOCAT_LINK
          value: "false"
        volumeMounts:
        - name: gogs-persistent-storage
          mountPath: /data
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      volumes:
      - name: gogs-persistent-storage
        persistentVolumeClaim:
          claimName: gogs-pvc-nfs
