apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-gogs-pv
  namespace: source-control
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 9Gi
  persistentVolumeReclaimPolicy: Retain
  nfs: 
    path: /mysqlgogs
    server: 10.112.42.52
    readOnly: false

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-gogs-pvc
  namespace: source-control
spec:
  accessModes:
  - ReadWriteMany
  resources:
     requests:
       storage: 9Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: source-control
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: gogs
        - name: MYSQL_USER
          value: gogs
        - name: MYSQL_PASSWORD
          value: pass
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-gogs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  namespace: source-control
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

