apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-gogs-pv
  namespace: source-control
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 9Gi
  persistentVolumeReclaimPolicy: Retain
  nfs: 
    path: /mysqlgogs
    server: 10.112.42.52
    readOnly: false

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-gogs-pvc
  namespace: source-control
spec:
  accessModes:
  - ReadWriteMany
  resources:
     requests:
       storage: 9Gi
